name: trufi_core
description: A Flutter Plugin for Public Transport.
version: 2.0.0
author: Trufi Association e.V.
homepage: https://www.trufi-association.org/
repository: https://github.com/trufi-association/trufi-core

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  app_review: ^2.1.1+1
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.3
  diff_match_patch: ^0.4.1
  equatable: ^2.0.3
  flare_flutter: ^3.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  flutter_compass: ^0.6.1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^0.13.1
  flutter_svg: ^0.22.0
  geolocator: ^7.3.0
  google_api_availability: ^3.0.1
  graphql: ^5.0.0
  http: ^0.13.3
  intl: ^0.17.0
  maps_toolkit: ^2.0.0
  package_info: ^2.0.2
  path_provider: ^2.0.2
  permission_handler: ^8.1.3
  rxdart: ^0.26.0
  share: ^2.0.4
  shared_preferences: ^2.0.6
  skeleton_animation: ^0.1.4
  sprintf: ^6.0.0
  synchronized: ^3.0.0
  url_launcher: ^6.0.9
  uuid: ^3.0.4
  xml: ^5.1.2


dev_dependencies:
  bloc_test: ^8.0.2
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.12
  network_image_mock: ^2.0.1
  plugin_platform_interface: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    androidPackage: app.trufi.trufi_core
    pluginClass: TrufiCorePlugin

  generate: true

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  assets:
    - assets/images/
    - assets/images/weather/
  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons/CustomIcons.ttf
